RNMT-3280 Troubleshoot ::: Define and implement solution
OutSystems/FLEX pull request #2
Opened 2019-10-24 10:22 UTC by usernuno

## Description

Disables simulator keyboard shortcuts.

## Context

Closes https://outsystemsrd.atlassian.net/browse/RNMT-3280

## Type of changes

- [x] Feature (change which adds functionality)
    - [ ] BREAKING CHANGE (existing functionality will not work as expected due to new feature)
- [ ] Fix (change which fixes an issue)
    - [ ] BREAKING CHANGE (existing functionality will not work as expected due to fix)
- [ ] Performance (change which improves performance)
    - [ ] BREAKING CHANGE (existing functionality will not work as expected due to performance improvement)
- [ ] Refactor (non-breaking change that is neither feature, fix nor performance)
- [ ] Style (non-breaking change that only affects formatting and/or white-space)

"Feature"

## Tests

## Screenshots (if appropriate)

## Checklist

- [x] Code follows code style of this project
- [ ] CHANGELOG.md file is correctly updated
- [ ] Changes require an update to the documentation
	- [ ] Documentation has been updated accordingly

2019-10-24 13:26 UTC, cmfsotelo requested changes
As this repository does not have a CHANGELOG.md, can i challenge **us** to create one to register our changes to the repository?

2019-10-24 14:26 UTC, pmaroco approved these changes
I agree with @cmfsotelo, add a CHANGELOG.md file and you're ready to go!

2019-10-25 17:25 UTC, usernuno commented
> As this repository does not have a CHANGELOG.md, can i challenge **us** to create one to register our changes to the repository?

The CHANGELOG.md was added.

2019-10-25 17:25 UTC, luissilvaos approved these changes

2019-10-25 17:26 UTC, merged